### ISSUE TITLE
Usage instructions not clear

### ISSUE THREAD

**Issue by ixxie** [tweag/npmlock2nix#44]
As a mere mortal NixOS user, I'm having a bit of a hard time getting started with npmlock2nix, and the README isn't very explicit on how to proceed.

First, the sample `shell.nix` file has a `<FIXME>` which I assumed meant that I should clone the repo and add it to my `NIX_PATH`; I did something like this:

```
  nix.nixPath = [
    "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos"
    "nixos-config=/etc/nixos/configuration.nix"
    "/nix/var/nix/profiles/per-user/root/channels"
    "npmlock2nix=/home/ixxie/repos/npmlock2nix"
  ];
```

and substituted `<npmlock2nix>` for the `<FIXME>`. After rebuilding and restarting the shell, my `NIX_PATH` seemed correct.

But when I try to run `nix-shell` I got `error: undefined variable 'npmlock2nix' at /home/ixxie/repos/myproject/shell.nix:2:1`. I then concluded that perhaps `nodelock2nix` was a typo or old project name in the README so I tried changing it to `npmlock2nix`, i.e. have a file like:

```
{ pkgs ? import <nixpkgs> {}, npmlock2nix ? <npmlock2nix> { inherit pkgs; } }:
npmlock2nix.shell {
  src = ./.;
  nodejs = pkgs.nodejs-14_x;
}
```

But this results in `error: attempt to call something which is not a function but a path, at /home/ixxie/repos/myproject/shell.nix:1:45`.

What am I doing wrong here?

**Comment by andir** [comment]
Thanks for trying. You are probably one of the first users so any feedback is welcome.

On 26 December 2020 15:54:34 CET, Matan Shenhav <notifications@github.com> wrote:
>As a mere mortal NixOS user, I'm having a bit of a hard time getting
>started with npmlock2nix, and the README isn't very explicit on how to
>proceed.
>
>First, the sample `shell.nix` file has a `<FIXME>` which I assumed
>meant that I should clone the repo and add it to my `NIX_PATH`; I did
>something like this:
>
>```
>  nix.nixPath = [
>    "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos"
>    "nixos-config=/etc/nixos/configuration.nix"
>    "/nix/var/nix/profiles/per-user/root/channels"
>    "npmlock2nix=/home/ixxie/repos/npmlock2nix"
>  ];
>```
>
>and substituted `<npmlock2nix>` for the `<FIXME>`. After rebuilding and
>restarting the shell, my `NIX_PATH` seemed correct.
>
>But when I try to run `nix-shell` I got `error: undefined variable
>'npmlock2nix' at /home/ixxie/repos/myproject/shell.nix:2:1`. I then
>concluded that perhaps `nodelock2nix` was a typo or old project name in
>the README so I tried changing it to `npmlock2nix`, i.e. have a file
>like:
>
>```
>{ pkgs ? import <nixpkgs> {}, npmlock2nix ? <npmlock2nix> { inherit
>pkgs; } }:

Add an import before <npmlock2nix>.

>npmlock2nix.shell {
>  src = ./.;
>  nodejs = pkgs.nodejs-14_x;
>}
>```
>
>But this results in `error: attempt to call something which is not a
>function but a path, at /home/ixxie/repos/coflow/shell.nix:1:45`.
>
>What am I doing wrong here?

**Comment by ixxie** [comment]
Thanks for the unbelievably fast response :smile: 

> Add an import before <npmlock2nix>.

:man_facepalming: can't believe I missed that!

**Comment by ixxie** [comment]
I'm 90% sure this isn't related to npmlock2nix, but now that the build works I get this:

```
[...]
building
90m..................] / rollbackFailedOptional: verb npm-session 7c5d0f9d32bc49c
> myproject@0.0.1 preinstall /build/myproject
> /build/myproject/node_modules/.hooks/preinstall
npm ERR! code ENOTCACHED install loadAllDepsIntoIdealTree
npm ERR! request to https://registry.npmjs.org/polka failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/myproject/.npm/_logs/2020-12-26T15_18_40_514Z-debug.log

builder for '/nix/store/fxhblr5b6rbzbz6mxj5y414f8b1pcz60-TODO-0.0.1.drv' failed with exit code 1
error: build of '/nix/store/fxhblr5b6rbzbz6mxj5y414f8b1pcz60-TODO-0.0.1.drv' failed
```

**Comment by ixxie** [comment]
Build now runs, thank you!
