### ISSUE TITLE
Jupyterlab javascript packages can have @ symbol

### ISSUE THREAD

**Issue by costrouc** [tweag/npmlock2nix#48]
**Describe the bug**

Unable to create `node_modules` from jupyterlab package `jupyterlab_toc`

**To Reproduce**
Steps to reproduce the behavior.

```
{ pkgs ? import <nixpkgs> {} }:

let nodelock2nix = (import (builtins.fetchTarball {
      url = "https://github.com/tweag/npmlock2nix/archive/7a321e2477d1f97167847086400a7a4d75b8faf8.tar.gz";
      sha256 = "10igdxcc6scf6hksjbbgpj877f6ry8mipz97r2v8j718wd233v6a";
    })) { inherit pkgs; };
in
nodelock2nix.shell {
  src = ./.;
  nodejs = pkgs.nodejs-14_x;
}
```

The `package.json` is copied from https://github.com/jupyterlab/jupyterlab-toc

```
npm install
```

```
nix-shell
```

```
error: The path name '@jupyterlab/toc-4fff.0.0' is invalid: the '@' character is invalid. Path names are alphanumeric and can include the symbols +-._?= and must not begin with a period. Note: If '@jupyterlab/toc-4.0.0' is a source file and you cannot rename it on disk, builtins.path { name = ... } can be used to give it an alternative name.
(use '--show-trace' to show detailed location information)
```

**Expected behavior**

Should create `node_modules`

**Environment**
 - OS name + version: nixos a somewhat recent commit
 - Version of the code: master

**Additional context**

I wanted to try this out in hopes that I could start packaging jupyterlab extensions for the 3.0 release. If this were to work we would be able fully build reproducibility jupyterlab extensions. Additional hope of this work is that we can start to build more python packages from the github source instead of pypi where they usually bundle in the npm dependencies.

**Comment by andir** [comment]
Did you create a package-lock.json or did you try the experimental yarn
lock branch of npmlock2nix?

**Comment by costrouc** [comment]
I was using the current master branch of npmlock2nix.

**Comment by costrouc** [comment]
I generated the package-lock.json file with `npm install`
