### ISSUE TITLE
Filter source for node_modules

### ISSUE THREAD

**Issue by shlevy** [tweag/npmlock2nix#77]
**Is your feature request related to a problem? Please describe.**
Currently, if I change any files in my project, I have to rebuild my whole `node_modules` (in my case, including a 5-mintue C++ compile)

**Describe the solution you'd like**
`npmlock2nix.build` could filter `src` before passing it to `node_modules`

**Describe alternatives you've considered**
Currently I'm using `node_modules_attrs.src` to work around thsi.

**Comment by andir** [comment]
Thanks for reporting this. I ran across this the other day myself. In fact I can't even recall why we actually capture `src` for the `node_modules` build at all. You can likely set `src` to `null` (or an empty dir) in that case and provide the original lock and package.json instead:

https://github.com/tweag/npmlock2nix/blob/1499b402eda50976435f5b1b0525dc7d0404900b/internal.nix#L226-L227

**Comment by shlevy** [comment]
Oh, it looks like the actual fix would just be removing `src` in the inherit line here https://github.com/tweag/npmlock2nix/blob/1499b402eda50976435f5b1b0525dc7d0404900b/internal.nix#L281
